server:  
  port: 4200  
#  ssl:
#    key-store: classpath:215074853670743.pfx
#    key-store-password: 215074853670743
#    keyStoreType: PKCS12
#spring
spring:
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: com.ant.be.support.JsonbPostgresDialect
      
  # jdbc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/ant-be
    username: postgres
    password: AAA111+++
    platform: postgres
    continue-on-error: true
    
    druid:
      initial-size: 5
      max-active: 50
      min-idle: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 100000
      async-close-connection-enable: true
      aop-patterns: com.ant.be.repository.*
      filter:
        stat:
          db-type: postgresql
          log-slow-sql: true
          slow-sql-millis: 2000
      
      
    
  session:
  #暂时不用redis，所以none，spring.session.store-type=reids  
    store-type: REDIS
  #redis
  redis:
    host: 127.0.0.1
    port: 4200
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 10000
    
    
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ant.be.entity
  
#配置分页插件pagehelper
pagehelper:
   helperDialect: postgresql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql    

  
